import {Hiragana} from '../level-management/hiragana';
export const HIRAGANAS: Hiragana[] = [
    { id: 1, romanji: 'a', hiragana: 'あ'},
    { id: 2, romanji: 'i', hiragana: 'い'},
    { id: 3, romanji: 'u', hiragana: 'う'},
    { id: 4, romanji: 'e', hiragana: 'え'},
    { id: 5, romanji: 'o', hiragana: 'お'},
    { id: 6, romanji: 'ka', hiragana: 'か'},
    { id: 7, romanji: 'ki', hiragana: 'き'},
    { id: 8, romanji: 'ku', hiragana: 'く'},
    { id: 9, romanji: 'ke', hiragana: 'け'},
    { id: 10, romanji: 'ko', hiragana: 'こ'},
    { id: 11, romanji: 'ga', hiragana: 'が'},
    { id: 12, romanji: 'gi', hiragana: 'ぎ'},
    { id: 13, romanji: 'gu', hiragana: 'ぐ'},
    { id: 14, romanji: 'ge', hiragana: 'げ'},
    { id: 15, romanji: 'go', hiragana: 'ご'},
    { id: 16, romanji: 'sa', hiragana: 'さ'},
    { id: 17, romanji: 'shi', hiragana: 'し'},
    { id: 18, romanji: 'su', hiragana: 'す'},
    { id: 19, romanji: 'se', hiragana: 'せ'},
    { id: 20, romanji: 'so', hiragana: 'そ'},
    { id: 21, romanji: 'za', hiragana: 'ざ'},
    { id: 22, romanji: 'ji (zi)', hiragana: 'じ'},
    { id: 23, romanji: 'zu', hiragana: 'ず'},
    { id: 24, romanji: 'ze', hiragana: 'ぜ'},
    { id: 25, romanji: 'zo', hiragana: 'ぞ'},
    { id: 26, romanji: 'ta', hiragana: 'た'},
    { id: 27, romanji: 'chi', hiragana: 'ち'},
    { id: 28, romanji: 'tsu', hiragana: 'つ'},
    { id: 29, romanji: 'te', hiragana: 'て'},
    { id: 30, romanji: 'to', hiragana: 'と'},
    { id: 31, romanji: 'da', hiragana: 'だ'},
    { id: 32, romanji: 'ji (di)', hiragana: 'ぢ'},
    { id: 33, romanji: 'zu (du)', hiragana: 'づ'},
    { id: 34, romanji: 'de', hiragana: 'で'},
    { id: 35, romanji: 'do', hiragana: 'ど'},
    { id: 36, romanji: 'na', hiragana: 'な'},
    { id: 37, romanji: 'ni', hiragana: 'に'},
    { id: 38, romanji: 'nu', hiragana: 'ぬ'},
    { id: 39, romanji: 'ne', hiragana: 'ね'},
    { id: 40, romanji: 'no', hiragana: 'の'},
    { id: 41, romanji: 'ha', hiragana: 'は'},
    { id: 42, romanji: 'hi', hiragana: 'ひ'},
    { id: 43, romanji: 'fu', hiragana: 'ふ'},
    { id: 44, romanji: 'he', hiragana: 'へ'},
    { id: 45, romanji: 'ho', hiragana: 'ほ'},
    { id: 46, romanji: 'ba', hiragana: 'ば'},
    { id: 47, romanji: 'bi', hiragana: 'び'},
    { id: 48, romanji: 'bu', hiragana: 'ぶ'},
    { id: 49, romanji: 'be', hiragana: 'べ'},
    { id: 50, romanji: 'bo', hiragana: 'ぼ'},
    { id: 51, romanji: 'ma', hiragana: 'ま'},
    { id: 52, romanji: 'mi', hiragana: 'み'},
    { id: 53, romanji: 'mu', hiragana: 'む'},
    { id: 54, romanji: 'me', hiragana: 'め'},
    { id: 55, romanji: 'mo', hiragana: 'も'},
    { id: 56, romanji: 'pa', hiragana: 'ぱ'},
    { id: 57, romanji: 'pi', hiragana: 'ぴ'},
    { id: 58, romanji: 'pu', hiragana: 'ぷ'},
    { id: 59, romanji: 'pe', hiragana: 'ぺ'},
    { id: 60, romanji: 'po', hiragana: 'ぽ'},
    { id: 61, romanji: 'ya', hiragana: 'や'},
    { id: 62, romanji: 'yu', hiragana: 'ゆ'},
    { id: 63, romanji: 'yo', hiragana: 'よ'},
    { id: 64, romanji: 'ra', hiragana: 'ら'},
    { id: 65, romanji: 'ri', hiragana: 'り'},
    { id: 66, romanji: 'ru', hiragana: 'る'},
    { id: 67, romanji: 're', hiragana: 'れ'},
    { id: 68, romanji: 'ro', hiragana: 'ろ'},
    { id: 69, romanji: 'wa', hiragana: 'わ'},
    { id: 70, romanji: 'o (wo)', hiragana: 'を'},
    { id: 71, romanji: 'n', hiragana: 'ん'},
]